--This is is the first table created to import data into postgres;
--it goes into the raw schema.

CREATE TABLE IF NOT EXISTS raw.dataco_supplychain_raw (
        Type TEXT,
        Days_for_shipping_real TEXT,
        Days_for_shipment_scheduled TEXT,
        Benefit_per_order TEXT,
        Sales_per_customer  TEXT,
        Delivery_Status TEXT,
        Late_delivery_risk TEXT,
        Category_Id TEXT,
        Category_Name TEXT,
        Customer_City TEXT,
        Customer_Country TEXT,
        Customer_Email TEXT,
        Customer_Fname TEXT,
        Customer_Id TEXT,
        Customer_Lname TEXT,
        Customer_Password TEXT,
        Customer_Segment TEXT,
        Customer_State TEXT,
        Customer_Street TEXT,
        Customer_Zipcode TEXT,
        Department_Id TEXT,
        Department_Name TEXT,
        Latitude TEXT,
        Longitude TEXT,
        Market TEXT,
        Order_City TEXT,
        Order_Country TEXT,
        Order_Customer_Id TEXT,
        order_date_DateOrders TEXT,
        Order_Id TEXT,
        Order_Item_Cardprod_Id TEXT,
        Order_Item_Discount TEXT,
        Order_Item_Discount_Rate TEXT,
        Order_Item_Id TEXT,
        Order_Item_Product_Price TEXT,
        Order_Item_Profit_Ratio TEXT,
        Order_Item_Quantity TEXT,
        Sales TEXT,
        Order_Item_Total TEXT,
        Order_Profit_Per_Order TEXT,
        Order_Region TEXT,
        Order_State TEXT,
        Order_Status TEXT,
        Order_Zipcode TEXT,
        Product_Card_Id TEXT,
        Product_Category_Id TEXT,
        Product_Description TEXT,
        Product_Image TEXT,
        Product_Name TEXT,
        Product_Price TEXT,
        Product_Status TEXT,
        shipping_date_DateOrders TEXT,
        Shipping_Mode TEXT
);