--clean table with correct data types and constraints

CREATE TABLE IF NOT EXISTS staging.dataco_supplychain_stg(
        load_id BIGSERIAL PRIMARY KEY,
        ingested_at TIMESTAMP NOT NULL DEFAULT now(),
        source_table TEXT NOT NULL DEFAULT 'raw.dataco_supplychain_raw',
        record_type TEXT NOT NULL,
        Days_for_shipping_real INTEGER,
        Days_for_shipment_scheduled INTEGER,
        Benefit_per_order NUMERIC(12,2),
        Sales_per_customer  NUMERIC(12,2),
        Delivery_Status TEXT,
        Late_delivery_risk BOOLEAN,
        Category_Id BIGINT,
        Category_Name TEXT,
        Customer_City TEXT,
        Customer_Country TEXT,
        Customer_Fname TEXT,
        Customer_Id BIGINT,
        Customer_Lname TEXT,
        Customer_Segment TEXT,
        Customer_State TEXT,
        Customer_Street TEXT,
        Customer_Zipcode TEXT,
        Department_Id BIGINT,
        Department_Name TEXT,
        Latitude NUMERIC(9,6),
        Longitude NUMERIC(9,6),
        Market TEXT,
        Order_City TEXT,
        Order_Country TEXT,
        Order_Customer_Id BIGINT,
        order_date_ts TIMESTAMP,
        Order_Id BIGINT,
        Order_Item_Cardprod_Id BIGINT,
        Order_Item_Discount NUMERIC(12,2),
        Order_Item_Discount_Rate NUMERIC(9,6),
        Order_Item_Id BIGINT,
        Order_Item_Product_Price NUMERIC(12,2),
        Order_Item_Profit_Ratio NUMERIC(9,6),
        Order_Item_Quantity INTEGER,
        Sales NUMERIC(12,2),
        Order_Item_Total NUMERIC(12,2),
        Order_Profit_Per_Order NUMERIC(12,2),
        Order_Region TEXT,
        Order_State TEXT,
        Order_Status TEXT,
        Order_Zipcode TEXT,
        Product_Card_Id BIGINT,
        Product_Category_Id BIGINT,
        Product_Description TEXT,
        Product_Name TEXT,
        Product_Price numeric(12,2),
        Product_Status INTEGER,
        shipping_date_ts TIMESTAMP,
        Shipping_Mode TEXT,
        dq_notes TEXT,

        CONSTRAINT uq_order_item UNIQUE (Order_Id, Order_Item_Id)
);